package io.dropwizard.primer.model;

public interface PrimerHttpHeaders {

    String AUTHORIZED_FOR_ID = "X-AUTHORIZED-FOR-ID";
    String AUTHORIZED_FOR_SUBJECT = "X-AUTHORIZED-FOR-SUBJECT";
    String AUTHORIZED_FOR_NAME = "X-AUTHORIZED-FOR-NAME";
    String AUTHORIZED_FOR_ROLE = "X-AUTHORIZED-FOR-ROLE";
    String AUTHORIZATION_TOKEN_TYPE = "X-AUTHORIZATION-TOKEN-TYPE";

}
